<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class laporan_program extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('laporan_program_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['title'] = 'Laporan Program';
        $data['subtitle'] = '';
        $data['crumb'] = [
            'Laporan Program' => '',
        ];

        $data['page'] = 'laporan_program/laporan_program_list';
        $this->load->view($this->config->item('template') . 'template/backend', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->laporan_program_model->json();
    }

    public function terima($id_ipm)
    {
        $data = array(
            'id_program_mahasiswa' => $id_ipm,
            'step' => '3',
            'created_at' => date('Y-m-d H:i:s'),
            'status' => '2',
        );
        $this->laporan_program_model->insert($data);
        $this->session->set_flashdata('message', 'Create Record Success');
        redirect(site_url('laporan_program'));
    }

    public function tolak($id_ipm)
    {
        $data = array(
            'id_program_mahasiswa' => $id_ipm,
            'step' => '3',
            'created_at' => date('Y-m-d H:i:s'),
            'status' => '0',
        );
        $this->laporan_program_model->insert($data);
        $this->session->set_flashdata('message', 'Create Record Success');
        redirect(site_url('laporan_program'));
    }
}

/* End of file laporan_program.php */
/* Location: ./application/controllers/laporan_program.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-30 08:15:01 */
/* http://harviacode.com */