<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class review_peserta extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('review_peserta_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['title'] = 'Review Peserta';
        $data['subtitle'] = '';
        $data['crumb'] = [
            'Review Peserta' => '',
        ];

        $data['page'] = 'review_peserta/review_peserta_list';
        $this->load->view($this->config->item('template') . 'template/backend', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->review_peserta_model->json();
    }

    public function terima($id_ipm)
    {
        $data = array(
            'id_program_mahasiswa' => $id_ipm,
            'step' => '3',
            'created_at' => date('Y-m-d H:i:s'),
            'status' => '2',
        );
        $this->review_peserta_model->insert($data);
        $this->session->set_flashdata('message', 'Create Record Success');
        redirect(site_url('review_peserta'));
    }

    public function tolak($id_ipm)
    {
        $data = array(
            'id_program_mahasiswa' => $id_ipm,
            'step' => '3',
            'created_at' => date('Y-m-d H:i:s'),
            'status' => '0',
        );
        $this->review_peserta_model->insert($data);
        $this->session->set_flashdata('message', 'Create Record Success');
        redirect(site_url('review_peserta'));
    }
}

/* End of file review_peserta.php */
/* Location: ./application/controllers/review_peserta.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-30 08:15:01 */
/* http://harviacode.com */