<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class V_milestone extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $c_url = $this->router->fetch_class();
        $this->layout->auth();
        $this->layout->auth_privilege($c_url);
        $this->load->model('V_milestone_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['v_milestone'] = $this->V_milestone_model->get_all();
        $data['title'] = 'View Data';
        $data['subtitle'] = 'Milestone';
        $data['crumb'] = [
            'V Milestone' => '',
        ];

        $data['page'] = $this->config->item('template') . 'v_milestone/v_milestone_list';
        $this->load->view($this->config->item('template') . 'template/backend', $data);
    }
}

/* End of file V_milestone.php */
/* Location: ./application/controllers/V_milestone.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-05 14:22:52 */
/* http://harviacode.com */