<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class V_project extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $c_url = $this->router->fetch_class();
        $this->layout->auth();
        $this->layout->auth_privilege($c_url);
        $this->load->model('V_project_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['v_project'] = $this->V_project_model->get_all();
        $data['title'] = 'View Data';
        $data['subtitle'] = 'Project';
        $data['crumb'] = [
            'V Project' => '',
        ];

        $data['page'] = $this->config->item('template') . 'v_project/v_project_list';
        $this->load->view($this->config->item('template') . 'template/backend', $data);
    }
}

/* End of file V_project.php */
/* Location: ./application/controllers/V_project.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-05 14:34:20 */
/* http://harviacode.com */