<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class V_client_model extends CI_Model
{

    public $table = 'v_client';
    public $id = 'name';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
}

/* End of file V_client_model.php */
/* Location: ./application/models/V_client_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-05 14:01:25 */
/* http://harviacode.com */