<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class V_milestone_model extends CI_Model
{

    public $table = 'v_milestone';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_date($date)
    {
        return $this->db->query("SELECT * FROM v_milestone WHERE SUBSTR(contract_date,1,7)='$date'")->result();
    }
}

/* End of file V_milestone_model.php */
/* Location: ./application/models/V_milestone_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-05 14:22:52 */
/* http://harviacode.com */